20231106
sayyah/ECommerce pull request #567
Opened 2023-11-06 05:21 UTC by Meysamhb

2023-11-06 09:35 UTC, pouryapb requested changes

2023-11-06 09:35 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Areas/Admin/Pages/Contacts/Index.cshtml
> +                                    <th scope="row">@(i++)</th>پ
Mistype at the end of line 70

2023-11-06 15:04 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Areas/Admin/Pages/Contacts/Index.cshtml
> +                                    <th scope="row">@(i++)</th>پ
I will resolve this issue on the branch 565

2023-11-06 15:05 UTC, sayyah approved these changes

2023-11-06 15:48 UTC, pouryapb approved these changes

2023-11-07 16:47 UTC, AliMozafari67 approved these changes

2023-11-08 08:46 UTC, sayyah approved these changes

2023-11-08 12:53 UTC, merged