Fixed #565 ddd layers and dot net 8
sayyah/ECommerce pull request #574
Opened 2023-11-06 20:12 UTC by sayyah

2023-11-06 21:25 UTC, pouryapb approved these changes
Well, it runs...!

2023-11-07 16:40 UTC, AliMozafari67 submitted a review, later dismissed

2023-11-08 14:48 UTC, SamanR86 submitted a review, later dismissed

2023-11-09 17:52 UTC, AliMozafari67 submitted a review, later dismissed

2023-11-10 20:54 UTC, pouryapb requested changes

2023-11-10 20:54 UTC, pouryapb commented on ECommerce.Application/ECommerce.Application.csproj
>      <Nullable>enable</Nullable>
should be net8.0. line 4

2023-11-10 20:54 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/appsettings.json
> +    //"BaseAddress": "https://localhost:7257/"
local default

2023-11-10 20:54 UTC, pouryapb commented on EcommerceTestProject/ECommerce.ControllersTests.csproj
net8.0 here as well. line 4

2023-11-10 21:04 UTC, pouryapb requested changes

2023-11-10 21:04 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Areas/Admin/Pages/Currencies/Index.cshtml
>              <div class="example-preview table-responsive
needs "> at the end of this line
```suggestion
            <div class="example-preview table-responsive">
```

2023-11-10 21:04 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Areas/Admin/Pages/ProductComments/Accept.cshtml
>                          <a class="btn btn-secondary" asp-Page="/ProductComments/index" asp-area="Admin">لغو</a>
at the end of this file missing this: >

2023-11-10 21:24 UTC, pouryapb requested changes

2023-11-10 21:24 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/_compareProductCard.cshtml
> +﻿@model ProductCompareViewModel
```suggestion
@using ECommerce.Application.ViewModels
@model ProductCompareViewModel
```

2023-11-10 21:24 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/_productDetailsCart.cshtml
> +﻿@model ProductIndexPageViewModel
```suggestion
@using ECommerce.Application.ViewModels
@model ProductIndexPageViewModel
```

2023-11-10 21:24 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/_productCard.cshtml
> +﻿@model ProductIndexPageViewModel
```suggestion
@using ECommerce.Application.ViewModels
@model ProductIndexPageViewModel
```

2023-11-10 21:24 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/_blogCard.cshtml
> +﻿@using Microsoft.AspNetCore.Mvc.TagHelpers
```suggestion
@using ECommerce.Application.ViewModels
```

2023-11-10 21:24 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Shared/_Layout.cshtml
> +﻿@inject IConfiguration Configuration;
```suggestion
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
```

2023-11-10 21:24 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/CartList/Default.cshtml
> +@model IEnumerable<PurchaseOrderViewModel>
```suggestion
@using ECommerce.Application.ViewModels
@model IEnumerable<PurchaseOrderViewModel>
```

2023-11-10 21:42 UTC, pouryapb requested changes

2023-11-10 21:42 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/CartList/Default.cshtml
> +@model IEnumerable<PurchaseOrderViewModel>
also line 53, should change to `TempData["cartAllPrice"] = allPrice.ToString();` or there will be errors.

2023-11-10 21:42 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/Username/Default.cshtml
> +﻿@model LoginViewModel
```suggestion
@using ECommerce.Application.ViewModels
@model LoginViewModel 
```

2023-11-10 21:42 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/CategoriesMenu/Default.cshtml
> +﻿@model List<CategoryParentViewModel>
```suggestion
@using ECommerce.Application.ViewModels
@model List<CategoryParentViewModel>
```

2023-11-10 21:42 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/BlogCategoriesMenu/Default.cshtml
> +﻿@model List<CategoryParentViewModel>
```suggestion
@using ECommerce.Application.ViewModels
@model List<CategoryParentViewModel>
```

2023-11-10 21:42 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Pages/Components/CategoriesMobile/Default.cshtml
> +﻿@model List<CategoryParentViewModel>
```suggestion
@using ECommerce.Application.ViewModels
@model List<CategoryParentViewModel>
```

2023-11-11 03:17 UTC, sayyah commented on ECommerce.Application/ECommerce.Application.csproj
>      <Nullable>enable</Nullable>
This project is deleted.

2023-11-11 03:17 UTC, sayyah commented on EcommerceTestProject/ECommerce.ControllersTests.csproj
This project is deleted.

2023-11-11 03:20 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Areas/Admin/Pages/Currencies/Index.cshtml
>              <div class="example-preview table-responsive
I fixed.

2023-11-11 03:21 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Areas/Admin/Pages/ProductComments/Accept.cshtml
>                          <a class="btn btn-secondary" asp-Page="/ProductComments/index" asp-area="Admin">لغو</a>
I fixed.

2023-11-11 03:26 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Pages/Components/CategoriesMobile/Default.cshtml
> +﻿@model List<CategoryParentViewModel>
I putted this namespace as a global namespace on project.

2023-11-11 03:26 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Pages/Components/BlogCategoriesMenu/Default.cshtml
> +﻿@model List<CategoryParentViewModel>
I putted this namespace as a global namespace on project.

2023-11-11 03:26 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Pages/Components/CategoriesMenu/Default.cshtml
> +﻿@model List<CategoryParentViewModel>
I putted this namespace as a global namespace on project.

2023-11-11 03:27 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Pages/Components/Username/Default.cshtml
> +﻿@model LoginViewModel
I putted this namespace as a global namespace on project.

2023-11-11 03:27 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Pages/Components/Username/Default.cshtml
> +﻿@model LoginViewModel
I putted this namespace as a global namespace on project.

2023-11-11 03:30 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Pages/Components/CartList/Default.cshtml
> +@model IEnumerable<PurchaseOrderViewModel>
I putted this namespace as a global namespace on project.

I fixed.

2023-11-11 04:00 UTC, AliMozafari67 approved these changes

2023-11-11 12:01 UTC, pouryapb approved these changes

2023-11-11 12:01 UTC, pouryapb submitted a review, later dismissed

2023-11-11 14:46 UTC, pouryapb approved these changes

2023-11-11 15:30 UTC, AliMozafari67 submitted a review, later dismissed

2023-11-11 15:52 UTC, pouryapb requested changes

2023-11-11 15:52 UTC, pouryapb commented on ECommerce.Front.BolouriGroup/Areas/Admin/Pages/_ViewImports.cshtml
>  @namespace ECommerce.Front.BolouriGroup.Areas.Admin.Pages
اینها رو هم پیدا کردم
```suggestion
@using ECommerce.Domain.Entities
@using ECommerce.Domain.Entities.Helper
@using ECommerce.Application.ViewModels
@namespace ECommerce.Front.BolouriGroup.Areas.Admin.Pages
```

2023-11-11 18:30 UTC, SamanR86 approved these changes

2023-11-11 18:43 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Areas/Admin/Pages/_ViewImports.cshtml
>  @namespace ECommerce.Front.BolouriGroup.Areas.Admin.Pages
I fixed.

2023-11-11 18:44 UTC, pouryapb submitted a review, later dismissed

2023-11-12 17:38 UTC, AliMozafari67 approved these changes

2023-11-13 09:43 UTC, Meysamhb approved these changes

2023-11-13 09:48 UTC, Moniy0o0 approved these changes

2023-11-13 09:58 UTC, Meysamhb approved these changes

2023-11-13 10:46 UTC, pouryapb approved these changes

2023-11-13 10:50 UTC, merged