Fixes #469-ProductAttributeTest
sayyah/ECommerce pull request #597
Opened 2023-11-18 17:44 UTC by AliMozafari67

2023-11-19 10:24 UTC, SamanR86 approved these changes

2023-11-19 10:25 UTC, SamanR86 approved these changes

2023-11-20 04:30 UTC, SamanR86 approved these changes

2023-11-20 04:30 UTC, SamanR86 approved these changes

2023-11-21 12:49 UTC, sayyah commented on ECommerce.Repository.UnitTests/Colors/ColorTests.cs
> +
چرا color اینجا تغییر کرده؟

2023-11-22 16:23 UTC, AliMozafari67 commented on ECommerce.Repository.UnitTests/Colors/ColorTests.cs
> +
چون خطا میداد

2023-12-14 04:17 UTC, SamanR86 approved these changes

2023-12-14 04:18 UTC, SamanR86 requested changes
-

2023-12-18 08:07 UTC, SamanR86 submitted a review, later dismissed

2023-12-22 10:53 UTC, closed without merging