Fixes #630 checkout address edit and unselect
sayyah/ECommerce pull request #640
Opened 2023-12-02 19:46 UTC by pouryapb

برای تست کردن: اضافه کردن آدرس جدید بعد از انتخاب یک آدرس، باید یک بار دیگر روی آدرس انتخاب شده کلیک کنید تا از انتخاب خارج یشه.
@meysamhb

Fixes #630

2023-12-03 11:13 UTC, sayyah commented on ECommerce.API/Controllers/SendInformationController.cs
> +            if (repetitive != null && repetitive.FirstOrDefault() != null && repetitive.FirstOrDefault()!.Id != sendInformation.Id)
از نظر مفهمومی با خط بالا چه فرق میکنه؟ یعنی در چه حالتی این 2 تا if باهم فرق میکنن؟

2023-12-03 11:13 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Pages/Checkout.cshtml
> +                            <input id="edit-btn" class="btn btn-primary mt-5" disabled type="button"
نتونستی بدونه دکمه ویرایش این رو درست کنی؟
یعنی وقتی آدرس رو تغییر داد و دکمه پرداخت رو زد، خودش ویرایش کنه؟ مشکل چی بود برای اجرای این کار؟

2023-12-03 11:18 UTC, pouryapb commented on ECommerce.API/Controllers/SendInformationController.cs
> +            if (repetitive != null && repetitive.FirstOrDefault() != null && repetitive.FirstOrDefault()!.Id != sendInformation.Id)
تایپ repetitive یه لیسته و این لیست میتونه خالی باشه و لزوما خودش null نیست. پس وقتی FirrsOrDefault رو صدا میزنیم ممکنه لیستمون خالی باشه پس مقدار null برمیگردونه و بعد سعی میکنیم روی null مقدار Id رو بگیریم که باعث میشه exception بندازه

2023-12-03 11:40 UTC, sayyah submitted a review, later dismissed

2023-12-03 11:41 UTC, Moniy0o0 approved these changes

2023-12-05 07:01 UTC, SamanR86 submitted a review, later dismissed

2023-12-09 05:22 UTC, SamanR86 approved these changes

2023-12-11 19:03 UTC, sayyah requested changes

2023-12-13 07:34 UTC, Moniy0o0 approved these changes

2023-12-13 11:29 UTC, sayyah approved these changes

2023-12-14 04:14 UTC, SamanR86 approved these changes

2023-12-18 11:38 UTC, Meysamhb approved these changes

2023-12-18 11:38 UTC, merged