Fixes #659 Hangfire for Sms
sayyah/ECommerce pull request #693
Opened 2024-01-10 09:08 UTC by SamanR86

2024-01-10 11:37 UTC, sayyah requested changes

2024-01-10 11:37 UTC, sayyah commented on ECommerce.Application.ViewModels/SmsIr.cs
> +    public int Status { get; set; } // Status Code in sms.ir/developer-web-service/rest-api
کامنت حذف بشه

2024-01-10 11:37 UTC, sayyah commented on ECommerce.Front.BolouriGroup/Pages/Invoice.cshtml.cs
> +                    await _userService.SendInvoiceSms(
این قسمت به سرویس اضافه بشه به طوری که یه پیام و یه لیست از شماره تلفن بگیره و براشون sms رو ارسال کنه

2024-01-10 12:00 UTC, SamanR86 commented on ECommerce.Front.BolouriGroup/Pages/Invoice.cshtml.cs
> +                    await _userService.SendInvoiceSms(
پیشنهاد میکنم اپ ستینگ اینطوری پیاده سازی بشه
  "InvoiceNumbers": {
    "Numbers" : "09112320727,09112223444,0911555555"
  }
  
  بعد یکبار GetValue انجام میشه و split میکنیم شماره ها رو
  اگه اوکی هست من برم تو کارش

2024-01-13 18:41 UTC, sayyah submitted a review, later dismissed

2024-01-15 18:45 UTC, AliMozafari67 approved these changes

2024-02-05 18:14 UTC, AliMozafari67 submitted a review, later dismissed

2024-02-06 11:46 UTC, Meysamhb submitted a review, later dismissed

2024-02-06 12:30 UTC, sayyah approved these changes

2024-02-24 18:21 UTC, AliMozafari67 approved these changes

2024-02-28 07:16 UTC, SamanR86 commented
@Meysamhb rebased

2024-02-28 10:30 UTC, Meysamhb commented
@sayyah 
Approve

2024-02-28 18:50 UTC, sayyah approved these changes

2024-02-29 04:44 UTC, Meysamhb approved these changes

2024-02-29 04:45 UTC, merged