Fixes #692 missing check for PriceId in PurchaseOrdersController
sayyah/ECommerce pull request #695
Opened 2024-01-11 15:46 UTC by pouryapb

Fixes #692

2024-01-13 18:38 UTC, sayyah submitted a review, later dismissed

2024-01-17 18:42 UTC, AliMozafari67 approved these changes

2024-01-27 13:03 UTC, Meysamhb commented
please resolved conflict and Rebase
@pouryapb

2024-01-27 13:14 UTC, pouryapb reviewed
done

2024-01-27 15:18 UTC, sayyah approved these changes

2024-01-27 16:32 UTC, AliMozafari67 submitted a review, later dismissed

2024-02-01 09:50 UTC, sayyah requested changes

2024-02-01 09:50 UTC, sayyah commented on ECommerce.API/Controllers/PurchaseOrdersController.cs
> +                    await unitOfWork.SaveAsync(cancellationToken);
در خط 500 داریم. اینجا چرا نیاز هست که اضافه کنیم؟

2024-02-01 09:50 UTC, sayyah commented on ECommerce.API/Controllers/PurchaseOrdersController.cs
> +                    await unitOfWork.SaveAsync(cancellationToken);
در خط 439 داریم. اینجا چرا نیاز هست که اضافه کنیم؟

2024-02-01 09:50 UTC, sayyah commented on ECommerce.API/Controllers/PurchaseOrdersController.cs
> +                    await unitOfWork.SaveAsync(cancellationToken);
در خط 439 داریم. اینجا چرا نیاز هست که اضافه کنیم؟

2024-02-01 09:50 UTC, sayyah commented on ECommerce.API/Controllers/PurchaseOrdersController.cs
> -            await unitOfWork.SaveAsync(cancellationToken);
بجای اون 2 تای بالا همین باید کفایت کنه

2024-02-01 11:07 UTC, pouryapb commented on ECommerce.API/Controllers/PurchaseOrdersController.cs
> +                    await unitOfWork.SaveAsync(cancellationToken);
در جواب همه اینها، چون ارور track کردن id میداد و نتیجه کار در نهایت در دیتابیس ذخیره نمیشد. تست کردم اگه entity رو سیو کنم بعد تغییر دادن آیا مشکل حل میشه؟ که شد.

2024-02-01 11:09 UTC, pouryapb commented on ECommerce.API/Controllers/PurchaseOrdersController.cs
> -            await unitOfWork.SaveAsync(cancellationToken);
اکسپشن میندازه اصلا نمی‌رسه به این

2024-02-01 17:30 UTC, pouryapb commented on ECommerce.API/Controllers/PurchaseOrdersController.cs
> +                    await unitOfWork.SaveAsync(cancellationToken);
حدس من:
اینجا purchaseOrder ایجاد میشه و پایین تر از id اون برای ساختن purchaseOrderDetail استفاده میشه.
چون اون entity هنوز ذخیره نشده، اینجا ارور میده.

2024-02-03 16:02 UTC, sayyah submitted a review, later dismissed

2024-02-03 18:37 UTC, AliMozafari67 submitted a review, later dismissed

2024-02-05 18:13 UTC, AliMozafari67 submitted a review, later dismissed

2024-02-05 18:46 UTC, sayyah submitted a review, later dismissed

2024-02-10 05:20 UTC, SamanR86 approved these changes

2024-02-12 08:34 UTC, sayyah approved these changes

2024-02-12 08:35 UTC, Meysamhb approved these changes

2024-02-12 08:37 UTC, Moniy0o0 approved these changes

2024-02-12 08:38 UTC, merged